#!/bin/bash
#--------------------------------------------------------------
# install docker clip command & microscan
# see document & plugins
# https://github.com/lukaszlach/clip
#--------------------------------------------------------------
set -e

# ------------------------------------------------------------------------
# variables
# ------------------------------------------------------------------------
NAME=`basename $0`
TOKEN=$1
IMAGE=$2
OUTPUT_CLIP=`docker info | grep clip`
OUTPUT_MICROSCAN=`docker info | grep microscan`

# check arguments
if [ -z $TOKEN ] || [ -z $IMAGE ]; then
    echo "# ------------------------------------------------------------------------"
    echo "# docker image microscan"
    echo "# ------------------------------------------------------------------------"
    echo "Please check README.md"
    echo "https://github.com/aquasecurity/microscanner"
    echo ""
    echo "USAGE: $NAME {token} {image}"
    exit 1
fi
# install check clip 
if [[ ! $OUTPUT_CLIP =~ ^.*clip:.*$ ]]; then
    mkdir -p ~/.docker/cli-plugins
    curl -sf https://raw.githubusercontent.com/lukaszlach/clip/master/docker-clip -o ~/.docker/cli-plugins/docker-clip
    chmod +x ~/.docker/cli-plugins/docker-clip
    # ls -ltr ~/.docker/cli-plugins
fi

# install check microscan 
if [[ ! $OUTPUT_MICROSCAN =~ ^.*microscan:.*$ ]]; then
    docker clip add lukaszlach/clips:microscan
fi

docker microscan --token $TOKEN $IMAGE
