#!/bin/bash
# ------------------------------------------------------------------------
# App Engine Deploy
# ------------------------------------------------------------------------

# ------------------------------------------------------------------------
# variables
# ------------------------------------------------------------------------
NAME=`basename $0`
APP_YAML=$1

if [ -n ${GOOGLE_CLOUD_KEYFILE_JSON} ] && [ -n ${PROJECT_ID} ]; then
    # gcloud authentication and install kubectl.
    /root/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${GOOGLE_CLOUD_KEYFILE_JSON}
    /root/google-cloud-sdk/bin/gcloud config set core/project ${PROJECT_ID}
else
    echo "you need to add GOOGLE_CLOUD_KEYFILE_JSON and PROJECT_ID environment."
    exit 1
fi

# check arguments
if [ -z $APP_YAML ]; then
    echo "USAGE: $NAME {path/app.yaml}"
fi

/root/google-cloud-sdk/bin/gcloud app deploy $APP_YAML --quiet
