#!/bin/bash
# ------------------------------------------------------------------------
# go static analysis
# ------------------------------------------------------------------------
set -e

# ------------------------------------------------------------------------
# variables
# ------------------------------------------------------------------------
# base path
BASEPATH=`dirname $0`
# error flag
ERR_FLG=0
# check go source directory
DIR=${1:-.}
if [ -z $DIR ]; then
    cd $DIR
fi
# output coverage directory
COVER_DIR=${2:-coverage}

echo "# ------------------------------------------------------------------------"
echo "# check go static analytics..."
echo "# ------------------------------------------------------------------------"
    # --out-format checkstyle \
golangci-lint run --tests=false \
    --issues-exit-code 0 \
    --disable-all \
    -c $BASEPATH/config/base.golangci.yml \
    ./...
if [ $? -eq 0 ]; then
    ERR_FLG=1
fi
echo "# ------------------------------------------------------------------------"
echo "# check go duplication/const/cyclomatics..."
echo "# ------------------------------------------------------------------------"
    # --out-format checkstyle \
golangci-lint run --tests=false \
    --issues-exit-code 0 \
    --disable-all \
    -c $BASEPATH/config/check.golangci.yml \
    ./...

echo "# ------------------------------------------------------------------------"
echo "# go test..."
echo "# ------------------------------------------------------------------------"
mkdir -p $COVER_DIR
go test $(go list ./... | grep -v /vendor/) -coverprofile=$COVER_DIR/coverage.out
go tool cover -html=$COVER_DIR/coverage.out -o $COVER_DIR/coverage.html
gocover-cobertura < $COVER_DIR/coverage.out > $COVER_DIR/coverage_cobertura.xml

echo "# ------------------------------------------------------------------------"
echo "# result"
echo "# ------------------------------------------------------------------------"
if [ $ERR_FLG -eq 1 ]; then
    echo "Static analysis failed..."
    exit 1
else
    echo "Static analysis successed..."
    exit 0
fi
