#!/bin/bash
set -eu

if [ "$DOCKER_TAG" == "latest" ]; then
    docker build -t ${IMAGE_NAME} --build-arg CLOUD_COMMANDS_VERSION=${CLOUD_COMMANDS_VERSION} .
else
    docker build --build-arg IMAGE_VERSION=${DOCKER_TAG} --build-arg CLOUD_COMMANDS_VERSION=${CLOUD_COMMANDS_VERSION} -t ${IMAGE_NAME} .
fi
