#!/bin/bash
# ------------------------------------------------------------------------
# App Engine Deploy
# ------------------------------------------------------------------------
cp -p cloud/gcp/app.yaml app.yaml
gcloud app deploy app.yaml --quiet
